In [3]:
q=[22,41,14,41,39,15]
print(max(q))

41


In [17]:
p=['j','x','n','k','e','x']

In [18]:
del(p[3:5])
print(p)

['j', 'x', 'n', 'x']


In [23]:
import numpy as np
x=np.array([14,21,24,24])
y=np.array([12,6,23,29])
z=np.array([x,y])
print(z.shape)

(2, 4)


In [24]:
x=np.array([14,21,24,24])
y=np.array([12,6,23,29])
z=np.array([x,y])
print(z.size)

8


In [26]:
store=np.array(['X','Z','Z','Z'])
cost=np.array([7,1,9,4])
select_cost=cost[store == 'X']
print(select_cost)

[7]


In [27]:
store=np.array(['X','Z','Z','Z'])
cost=np.array([7,1,9,4])
select_cost=cost[store == 'Z']
print(select_cost)

[1 9 4]


In [28]:
X=6
Y=4
print(X%Y)

2


In [29]:
X=6
Y=4
print(X/Y)

1.5


In [30]:
store=np.array([0,9,0,1])
cost=np.array([82,82,73,73])
np_cols=np.column_stack((store,cost))
print(np_cols)

[[ 0 82]
 [ 9 82]
 [ 0 73]
 [ 1 73]]


In [31]:
p= [[3,'A',5],[2,6,'B'],['C','D','E']]
print(p[1][2])

B


In [32]:
p= [[3,'A',5],[2,6,'B'],['C','D','E']]
print(p[1][1])

6


In [33]:
p= [[3,'A',5],[2,6,'B'],['C','D','E']]
print(p[1][0:2])

[2, 6]


In [34]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [36]:
p=8.32592
print(int(p))

8


For finding the correlation between x and y we should use 'np.corrcoef' function.

In [39]:
x=np.array([6,4,4,4])
y=np.array([0,3,8,7])

print(np.corrcoef(x,y))

[[ 1.         -0.81150267]
 [-0.81150267  1.        ]]


In [40]:
Easy = ["Take", "Care", "of", 111, 2, 3.33, 00]
print ("Number of items in the list = ", len(Easy))

Number of items in the list =  7


In [41]:
list = [11, 21, 31, 'exam', 3.1321, 101, 301]
del list[6] #delete element at index 6
print(list)
list.remove('exam') #remove element with value
print(list)
a = list.pop(1) #pop element from list
print('Popped Element: ', a, ' List remaining: ', list)
list.clear() #empty the list
print(list)

[11, 21, 31, 'exam', 3.1321, 101]
[11, 21, 31, 3.1321, 101]
Popped Element:  21  List remaining:  [11, 31, 3.1321, 101]
[]


In [43]:
tuple = (10, 20, 30, 'education') #access elements
for access in tuple:
    print(access)
print(tuple)
print(tuple[0])
print(tuple[:])
print(tuple[3][4])

10
20
30
education
(10, 20, 30, 'education')
10
(10, 20, 30, 'education')
a


In [46]:
list = [11, 21, 31, 'exam', 3.1321, 101, 301]
del list[6] #delete element at index 6

In [47]:
list

[11, 21, 31, 'exam', 3.1321, 101]